{% set version = "2.18" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 103df36dc21081b7205d763ef7705e340eb0ea7e18694239b328a549892cc007  # [linux64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: a48160539c27c6a35413667b064f9af154d59ad592563dcaab8a07d427bda594  # [aarch64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.zip  # [osx]
  sha256: 55bd37ef2a3941a7af65f72e94dc8de4e9e4f179a93909d6ecc24c55a4ef4255  # [osx]

  fn: pandoc.msi  # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: afbcaa39a85bd44be89346036e09fe31db5712281c42ef384f1f86c97eea9745  # [win]

build:
  number: 0
  binary_relocation: false  # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter (repackaged binaries)
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/blob/master/MANUAL.txt

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - kiwi0fruit
