{% set version = "2.11.3.2" %}

package:
  name: pandoc
  version: {{ version }}  # [not ppc64le]
  version: 2.2.1  # [ppc64le]

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 422c1f38b4731edfafcc0f8011a8dc46ce3a84e61b896ef15e3a23e0a9b453d6  # [linux64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.zip  # [osx]
  sha256: 24487d8d495b3c126126559fe15617b21353b9356ee6dc41176fc931c1615a7a  # [osx]

  fn: pandoc.msi  # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: 35f321b612fb2beb0abd174a413adb2ab54f72fc1729f002ee045d4fec212de6  # [win]

  # repackage the RPM built for EPEL
  url: https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc/epel-7-ppc64le/00770404-pandoc/pandoc-2.2.1-1.el7.ppc64le.rpm  # [ppc64le]
  sha256: 5a9818493f8b14821c5fb44234c898f776faf011089dc77e1dcf6ba3e51e0a81  # [ppc64le]

build:
  number: 0
  binary_relocation: false  # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

# The pandoc binary from the RPM depends on libgmp, libz and libffi and system libraries.
# Add these as host requirements to pick up the correct run_exports
{% if ARCH == "ppc64le" %}
requirements:
  build:
    - patchelf
    - {{ compiler('c') }}
  host:
    - gmp 6.1.2
    - zlib 1.2.11
    - libffi 3.3
{% endif %}

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Universal markup converter (repackaged binaries)
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/tree/master/doc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - kiwi0fruit
