provider:
  win: azure
  linux_aarch64: default
build_platform:
  linux_aarch64: linux_aarch64
  osx_arm64: osx_64
test: native
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
